show databases;
use projectdb;
select * from mytable;

-- Q1 What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount_usd) as Total_revenue
from mytable
group by gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount_usd, (select avg(purchase_amount_usd) from mytable) from mytable
where discount_applied = 'Yes' and purchase_amount_usd > (select avg(purchase_amount_usd) from mytable);

-- Q3 which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 Compare the average purchase amount between standard and express shipping?
  select round(avg(purchase_amount_usd),2),shipping_type from mytable
  where shipping_type in ('Express','Standard')
  group by shipping_type;
  
-- Q5 Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers
   select round(avg(purchase_amount_usd),2), sum(purchase_amount_usd),subscription_status from mytable
   group by subscription_status;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied?
     select item_purchased,  round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as disc_perc
     from mytable
     group by item_purchased
     order by disc_perc desc
     limit 5;
     
-- Q7 Segment customers into new, returning, and loyal based on their total number of previous purchases, 
-- and show the count of each segment.
   with customer_type as
   (select customer_id, previous_purchases, case
   when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
from mytable)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- Q8 What are the top 3 most purchased products within each category?
 with item_counts as (
 select category,
 item_purchased,
 count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from mytable
 group by category, item_purchased
 )
 
 select item_rank, category, item_purchased, total_orders
 from item_counts
 where item_rank<=3;
 
 -- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
      WITH customer_type AS (
    SELECT
        customer_id,
        subscription_status,
        CASE
            WHEN previous_purchases > 5 THEN 'Repeat Buyers'
            ELSE 'Non Repeat Buyers'
        END AS customer_type
    FROM mytable
)

SELECT
    customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE
            WHEN subscription_status = 'Yes' THEN 1
            ELSE 0
        END) AS subscribed_customers
FROM customer_type
GROUP BY customer_type;

-- Q10 What is the revenue contribution of each age group?
select age_group, sum(purchase_amount_usd) as total_revenue from mytable
group by age_group
order by total_revenue desc;
